services:
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    container_name: turbo-starter-backend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3000:3000"

  dashboard:
    build:
      context: .
      dockerfile: apps/dashboard/Dockerfile
    container_name: turbo-starter-dashboard
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3001:3001"
    depends_on:
      - backend
